/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'iconmaster' at '7/4/16 5:40 PM' with Gradle 2.13
 *
 * @author iconmaster, @date 7/4/16 5:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
